swagger: '2.0'
info:
  version: ''
  title: Currencies
  description: >-

    - [OAuth Scopes](#oauth-scopes)

    - [Authentication](#authentication)

    - [Available Endpoints](#available-endpoints)

    - [Definitions](#definitions)

    - [FAQ](#faq)

    - [Resources](#resources)


    Manage alternate currency display options on the storefront.


    ## OAuth Scopes

    | UI Name                                      | Permission |
    Parameter                                     |

    |----------------------------------------------|------------|-----------------------------------------------|

    | Information & Settings                       | modify     |
    `store_v2_information`                        |

    | Information & Settings                       | read-only  |
    `store_v2_information_read_only`              |


    For more information on OAuth Scopes, see:
    [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication).


    ## Authentication


    Requests can be authenticated by sending a `client_id` and `access_token`
    via `X-Auth-Client` and `X-Auth-Token` HTTP headers:


    ```http

    GET /stores/{$$.env.store_hash}/v3/catalog/summary

    host: api.bigcommerce.com

    Accept: application/json

    X-Auth-Client: {client_id}

    X-Auth-Token: {access_token}

    ```


    |Header|Parameter|Description|

    |-|-|-|

    |`X-Auth-Client`|`client_id`|Obtained by creating an API account or
    installing an app in a BigCommerce control panel.|

    |`X-Auth-Token`|`access_token `|Obtained by creating an API account or
    installing an app in a BigCommerce control panel.|


    For more information on Authenticating BigCommerce APIs, see:
    [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication).


    ## Available Endpoints

    | Resource / Endpoint                     |
    Description                                                             |

    |-----------------------------------------|-------------------------------------------------------------------------|

    | Currencies                              | Create and manage store
    currencies and their display                    |


    ## Definitions


    | Name | Description |

    | -- | -- |

    | Default Currency | Store's default currency is the one from which any
    auto-conversion of pricing (product, tax, shipping, promotions) will
    happen.|

    | Display Currency | Currency that is displayed on the storefront. This
    might or might not mean that shopper can actually transact in that currency.
    Display currency is also often called "presentment currency" in the payments
    industry. |

    | Transactional Currency | Transactional currency is what currency and
    amount BC passes to the payment provider and the currency/amount that the
    shopper will be charged to their bank account. If there's a discrepancy
    between the storefront display currency and the transactional currency, a
    shopper has to pay a conversion fee and the conversion rate that will be
    used will be outside of BC's purview. |

    | Settlement Currency | This is the currency in which the merchant gets paid
    out to their bank account. If there's a discrepancy between the currency
    that shopper transacts in and the currency in which merchant settles,
    merchant has to pay a conversion fee and the conversion rate used will be
    outside of BC's purview. Merchant is able to set their settlement currency
    through their payment provider. |

    |BigCommerce Conversion Rate | Any conversion rate set on BigCommerce used
    to convert product’s default currency pricing into a new non-default
    currency. Conversion rate could be static or dynamic. |

    | Static Conversion Rate | One of the two auto-converted pricing options. If
    a merchant manually enters a static conversion rate, then the conversion
    rate will remain the same until/unless merchant updates their currency
    settings to use a different conversion rate. The advantage of using this
    method is to avoid constantly fluctuating price in non-default currencies. |

    | Dynamic Conversion Rate | One of the two auto-converted pricing options.
    If a merchant selects a dynamic conversion rate, they've tied themselves to
    a currency conversion service, which will update the conversion rate at a
    certain frequency. This helps shopper-facing pricing remain most aligned to
    the store's default currency and keeps non-default currency conversion rate
    at market rate. Merchant can either use BigCommerce Currency Service
    provided in the Currency setup page, or they can use API to automatically
    update the exchange rate from their trusted source. |

    | Bank Conversion Rate | Conversion rate used by merchant’s or shopper’s
    payment or credit card provider when auto-converting from store’s
    transactional currency. This rate might not align to the BC conversion rate
    and BC has no visibility into it. |

    | Multi Currency Pricing | Rather than opting for auto-converting product
    pricing from default currency using BC conversion rate, merchant has a
    choice to set price per product per currency. This will be implemented
    through price lists. |


    ## FAQ


    **Do Multi-Currency settings work with the Checkout SDK?**  

    The Checkout SDK works with multi-currency. There is no additional setup
    needed for the SDK.

    After setting up currency in the Control Panel the SDK will work as normal.


    ## Resources


    - [How Currencies
    Works](https://developer.bigcommerce.com/api-docs/catalog/currencies/how-currencies-work)

    - [Price List
    API](https://developer.bigcommerce.com/api-reference/catalog/pricelists-api)

    - [Using Price Lists](https://support.bigcommerce.com/s/article/Price-Lists)
    (BigCommerce Knowledge Base)

    - [Managing
    Currencies](https://support.bigcommerce.com/s/article/Managing-Currencies-Beta)
    (BigCommerce Knowledge Base)

    - [Tax](https://support.bigcommerce.com/s/article/Manual-Tax-Setup#intro1)
    (BigCommerce Knowledge Base)
host: api.bigcommerce.com
basePath: '/stores/{$$.env.store_hash}/v2/'
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /currencies:
    get:
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/Currency'
          examples:
            Example:
              - id: 1
                is_default: true
                last_updated: 'Fri, 11 May 2018 16:58:57 +0000'
                country_iso2: US
                currency_code: USD
                currency_exchange_rate: '1.0000000000'
                name: US Dollars
                token: $
                auto_update: false
                token_location: left
                decimal_token: .
                thousands_token: ','
                decimal_places: 2
                enabled: true
              - id: 2
                is_default: false
                last_updated: 'Fri, 10 Aug 2018 14:47:03 +0000'
                country_iso2: EU
                currency_code: EUR
                currency_exchange_rate: '0.8729000000'
                name: Euro
                token: €
                auto_update: true
                token_location: left
                decimal_token: .
                thousands_token: ','
                decimal_places: 2
                enabled: true
              - id: 3
                is_default: false
                last_updated: 'Fri, 10 Aug 2018 14:47:03 +0000'
                country_iso2: AU
                currency_code: AUD
                currency_exchange_rate: '1.3678000000'
                name: Aus
                token: $
                auto_update: true
                token_location: left
                decimal_token: .
                thousands_token: ','
                decimal_places: 2
                enabled: false
            example-2: {}
      summary: Get all Currencies
      description: Returns a list of all store *Currency*.
      tags:
        - Currencies
      produces:
        - application/json
      parameters:
        - name: Accept
          in: header
          type: string
          default: application/json
          required: true
        - name: Content-Type
          in: header
          type: string
          default: application/json
          required: true
    delete:
      responses:
        '204':
          description: ''
          schema:
            type: object
            properties: {}
      summary: Delete all Currencies
      parameters:
        - in: header
          name: Content-Type
          type: string
          default: application/json
          required: true
        - in: header
          name: Accepts
          type: string
          default: application/json
          required: true
      tags:
        - Currencies
      description: Deletes all non-default store currencies.
    post:
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Currency'
          examples:
            application/json:
              id: 3
              is_default: 'false'
              date_created: 'Thu, 11 Sep 2014 17:10:12 +0000'
              date_modified: 'Thu, 08 Jan 2015 15:12:48 +0000'
              country_iso2: AU
              currency_code: AUD
              currency_exchange_rate: '1.3885600000'
              auto_update: 'false'
              location: left
              token: $
              decimal_token: .
              thousands_token: ','
              decimal_places: 2
            Response Schema:
              country_iso2: ut
              currency_code: labore in culpa
              currency_exchange_rate: in proident tempor laborum cillum
              auto_update: false
              token_location: sit
              token: irure
              decimal_token: consequat
              thousands_token: nulla esse laborum mollit eiusmod
              decimal_places: 78912848
              name: irure ut ipsum
              id: -78012173
              is_default: true
              last_updated: '1949-11-24T17:38:14.674Z'
              enabled: false
      summary: Create a Currency
      description: >-
        Creates *Currency*.


        **Required Fields** 


        * country_iso2

        * currency_code

        * currency_exchange_rate

        * auto_update

        * token_location

        * token

        * decimal_token

        * thousands_token

        * decimal_places


        **Read-Only Fields**


        * id

        * is_default

        * date_created

        * date_modified



        The `is_default` property cannot be set programmatically. To change the
        store's default currency via the BigCommerce control panel, please see
        [Managing
        Currencies](https://support.bigcommerce.com/articles/Public/Managing-Currencies/?q=currency&l=en_US&fs=Search&pn=1#default).
      parameters:
        - name: Accept
          in: header
          type: string
          default: application/json
          required: true
        - name: Content-Type
          in: header
          type: string
          default: application/json
          required: true
        - in: body
          name: body
          schema:
            $ref: '#/definitions/Currency'
          x-examples:
            Example:
              country_iso2: AU
              currency_code: AUD
              currency_exchange_rate: '1.3885600000'
              auto_update: 'false'
              location: left
              token: $
              decimal_token: .
              thousands_token: ','
              decimal_places: 2
          description: ''
      tags:
        - Currencies
  '/currencies/{id}':
    get:
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Currency'
          examples:
            Example:
              id: 3
              is_default: 'false'
              date_created: 'Thu, 11 Sep 2014 17:10:12 +0000'
              date_modified: 'Thu, 08 Jan 2015 15:12:48 +0000'
              country_iso2: AU
              currency_code: AUD
              currency_exchange_rate: '1.3885600000'
              auto_update: 'false'
              location: left
              token: $
              decimal_token: .
              thousands_token: ','
              decimal_places: 2
      summary: Get a Currency
      description: Returns a single *Currency*.
      tags:
        - Currencies
      parameters:
        - name: Content-Type
          in: header
          type: string
          default: application/json
          required: true
        - name: Accept
          in: header
          type: string
          default: application/json
          required: true
      operationId: getACurrency
    parameters:
      - name: id
        in: path
        type: string
        required: true
        description: Currency Id
    put:
      responses:
        '200':
          description: ''
          schema:
            title: Currency
            example:
              id: 2
              is_default: false
              last_updated: 'Tue, 12 Jun 2018 14:41:56 +0000"'
              country_iso2: EU
              currency_code: EUR
              currency_exchange_rate: 0.849
              auto_update: true
              token_location: left
              token: €
              decimal_token: .
              thousands_token: ','
              decimal_places: 2
              name: Euro
              enabled: false
            type: object
            properties:
              id:
                description: Id of the currency. READ-ONLY
                example: 2
                type: integer
              is_default:
                description: >-
                  Specifies whether this is the store’s default currency display
                  format and may only be adjusted in the control panel.
                  READ-ONLY
                example: false
                type: boolean
              last_updated:
                description: 'Date the currency was last updated, created or modified.'
                example: 'Tue, 12 Jun 2018 14:41:56 +0000"'
                type: string
                format: date-time
              country_iso2:
                type: string
                description: 2-letter ISO Alpha-2 code for this currency’s country.
                example: EU
              currency_code:
                type: string
                description: 3-letter ISO 4217 code for this currency.
                example: EUR
              currency_exchange_rate:
                type: string
                description: >-
                  Amount of this currency that is equivalent to one U.S.
                  dollar.(Float, Float as String, Integer)
                example: 0.849
              auto_update:
                type: boolean
                description: >-
                  Specifies whether to use the Open Exchange Rates service to
                  update the currency conversion. A value of false specifies a
                  static conversion value.
                example: true
              token_location:
                type: string
                description: >-
                  Specifies whether this currency’s symbol appears to the “left”
                  or “right” of the numeric amount.
                example: left
              token:
                type: string
                description: Symbol for this currency.
                example: €
              decimal_token:
                type: string
                description: Symbol used as the decimal separator in this currency.
                example: .
              thousands_token:
                type: string
                description: Symbol used as the thousands separator in this currency.
                example: ','
              decimal_places:
                type: integer
                description: Number of decimal places to show for this currency.
                example: 2
              name:
                type: string
                description: Name of the currency.
                example: Euro
              enabled:
                description: If the currency is active on the store.
                example: false
                type: boolean
            required:
              - country_iso2
              - currency_code
              - currency_exchange_rate
              - auto_update
              - token_location
              - token
              - decimal_token
              - thousands_token
              - decimal_places
              - name
          examples:
            application/json:
              id: 3
              is_default: 'false'
              date_created: 'Thu, 11 Sep 2014 17:10:12 +0000'
              date_modified: 'Thu, 08 Jan 2015 15:12:48 +0000'
              country_iso2: AU
              currency_code: AUD
              currency_exchange_rate: '1.3885600000'
              auto_update: 'false'
              location: left
              token: $
              decimal_token: .
              thousands_token: ','
              decimal_places: 2
            Response Schema:
              country_iso2: ullamco
              currency_code: Lorem
              currency_exchange_rate: ut
              auto_update: false
              token_location: ut eu consequat mollit
              token: qui Excepteur occaecat nulla
              decimal_token: in Excepteur mollit
              thousands_token: cillum id
              decimal_places: -70119370
              name: ullamco magna amet tempor pariatur
              id: 70177765
              is_default: true
              last_updated: '1947-12-04T17:27:38.508Z'
              enabled: true
      summary: Update a Currency
      description: |-
        Updates a *Currency*.

        **Read-Only Fields**

        * id
        * is_default
        * date_created
        * date_modified
        * location
        * currency_code
      parameters:
        - name: Accept
          in: header
          type: string
          default: application/json
          required: true
        - name: Content-Type
          in: header
          type: string
          default: application/json
          required: true
        - in: body
          name: body
          schema:
            title: Currency
            example:
              id: 2
              is_default: false
              last_updated: 'Tue, 12 Jun 2018 14:41:56 +0000"'
              country_iso2: EU
              currency_code: EUR
              currency_exchange_rate: 0.849
              auto_update: true
              token_location: left
              token: €
              decimal_token: .
              thousands_token: ','
              decimal_places: 2
              name: Euro
              enabled: false
            type: object
            properties:
              id:
                description: Id of the currency. READ-ONLY
                example: 2
                type: integer
              is_default:
                description: >-
                  Specifies whether this is the store’s default currency display
                  format and may only be adjusted in the control panel.
                  READ-ONLY
                example: false
                type: boolean
              last_updated:
                description: 'Date the currency was last updated, created or modified.'
                example: 'Tue, 12 Jun 2018 14:41:56 +0000"'
                type: string
                format: date-time
              country_iso2:
                type: string
                description: 2-letter ISO Alpha-2 code for this currency’s country.
                example: EU
              currency_code:
                type: string
                description: 3-letter ISO 4217 code for this currency. READ-ONLY
                example: EUR
              currency_exchange_rate:
                type: string
                description: >-
                  Amount of this currency that is equivalent to one U.S.
                  dollar.(Float, Float as String, Integer)
                example: 0.849
              auto_update:
                type: boolean
                description: >-
                  Specifies whether to use the Open Exchange Rates service to
                  update the currency conversion. A value of false specifies a
                  static conversion value.
                example: true
              token_location:
                type: string
                description: >-
                  Specifies whether this currency’s symbol appears to the “left”
                  or “right” of the numeric amount.
                example: left
              token:
                type: string
                description: Symbol for this currency.
                example: €
              decimal_token:
                type: string
                description: Symbol used as the decimal separator in this currency.
                example: .
              thousands_token:
                type: string
                description: Symbol used as the thousands separator in this currency.
                example: ','
              decimal_places:
                type: integer
                description: Number of decimal places to show for this currency.
                example: 2
              name:
                type: string
                description: Name of the currency.
                example: Euro
              enabled:
                description: If the currency is active on the store.
                example: false
                type: boolean
            required:
              - country_iso2
              - currency_exchange_rate
              - auto_update
              - token_location
              - token
              - decimal_token
              - thousands_token
              - decimal_places
              - name
          x-examples:
            application/json:
              country_iso2: AU
              currency_code: AUD
              currency_exchange_rate: '1.3885600000'
              auto_update: 'false'
              location: left
              token: $
              decimal_token: .
              thousands_token: ','
              decimal_places: 2
      tags:
        - Currencies
      operationId: updateACurrency
    delete:
      responses:
        '204':
          description: ''
          schema:
            type: object
            properties: {}
      summary: Delete a Currency
      description: Deletes a *Currency*.
      tags:
        - Currencies
      parameters:
        - name: Accept
          in: header
          type: string
          default: application/json
          required: true
        - name: Content-Type
          in: header
          type: string
          default: application/json
          required: true
      operationId: deleteACurrency
definitions:
  Currency:
    title: Currency
    example:
      id: 2
      is_default: false
      last_updated: 'Tue, 12 Jun 2018 14:41:56 +0000"'
      country_iso2: EU
      currency_code: EUR
      currency_exchange_rate: 0.849
      auto_update: true
      token_location: left
      token: €
      decimal_token: .
      thousands_token: ','
      decimal_places: 2
      name: Euro
      enabled: false
    type: object
    x-examples:
      Example:
        value:
          country_iso2: EU
          currency_code: EUR
          currency_exchange_rate: '0.849'
          auto_update: true
          token_location: left
          token: €
          decimal_token: .
          thousands_token: ','
          decimal_places: 2
          name: Euro
          is_transactional: false
          id: 2
          is_default: false
          last_updated: '2018-06-12T14:41:56.000Z'
          enabled: false
    properties:
      id:
        description: Id of the currency. READ-ONLY
        example: 2
        type: integer
      is_default:
        description: >-
          Specifies whether this is the store’s default currency display format
          and may only be adjusted in the control panel. READ-ONLY
        example: false
        type: boolean
      last_updated:
        description: 'Date the currency was last updated, created or modified.'
        example: 'Tue, 12 Jun 2018 14:41:56 +0000"'
        type: string
        format: date-time
      country_iso2:
        type: string
        description: 2-letter ISO Alpha-2 code for this currency’s country.
        example: EU
      currency_code:
        type: string
        description: 3-letter ISO 4217 code for this currency.
        example: EUR
      currency_exchange_rate:
        type: string
        description: >-
          Amount of this currency that is equivalent to one U.S. dollar.(Float,
          Float as String, Integer)
        example: 0.849
      auto_update:
        type: boolean
        description: >-
          Specifies whether to use the Open Exchange Rates service to update the
          currency conversion. A value of false specifies a static conversion
          value.
        example: true
      token_location:
        type: string
        description: >-
          Specifies whether this currency’s symbol appears to the “left” or
          “right” of the numeric amount.
        example: left
      token:
        type: string
        description: Symbol for this currency.
        example: €
      decimal_token:
        type: string
        description: Symbol used as the decimal separator in this currency.
        example: .
      thousands_token:
        type: string
        description: Symbol used as the thousands separator in this currency.
        example: ','
      decimal_places:
        type: integer
        description: Number of decimal places to show for this currency.
        example: 2
      name:
        type: string
        description: Name of the currency.
        example: Euro
      enabled:
        description: If the currency is active on the store.
        example: false
        type: boolean
      is_transactional:
        type: boolean
        description: >-
          Indicates if the currency is set as transactional or not. False means
          display only currency
        example: false
    required:
      - country_iso2
      - currency_code
      - currency_exchange_rate
      - auto_update
      - token_location
      - token
      - decimal_token
      - thousands_token
      - decimal_places
      - name
      - is_transactional
    description: Currency Object
tags:
  - name: /currencies
    description: ''
  - name: Currencies
securityDefinitions:
  X-Auth-Token:
    type: apiKey
    name: X-Auth-Token
    in: header
    description: >-
      ### OAuth Scopes

      |  **UI Name** | **Permission** | **Parameter** |

      | --- | --- | --- |

      |  Information & Settings | modify | `store_v2_information` |

      |  Information & Settings | read-only | `store_v2_information_read_only` |


      ### Headers


      |Header|Parameter|Description|

      |-|-|-|

      |`X-Auth-Client`|`client_id`|Obtained by creating an API account or
      installing an app in a BigCommerce control panel.|

      |`X-Auth-Token`|`access_token `|Obtained by creating an API account or
      installing an app in a BigCommerce control panel.|


      ### Example


      ```http

      GET /stores/{$$.env.store_hash}/v3/catalog/summary

      host: api.bigcommerce.com

      Content-Type: application/json

      X-Auth-Client: {client_id}

      X-Auth-Token: {access_token}

      ```


      * For more information on Authenticating BigCommerce APIs, see:
      [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication). 
  X-Auth-Client:
    type: apiKey
    name: X-Auth-Client
    in: header
    description: >-
      ### OAuth Scopes

      |  **UI Name** | **Permission** | **Parameter** |

      | --- | --- | --- |

      |  Information & Settings | modify | `store_v2_information` |

      |  Information & Settings | read-only | `store_v2_information_read_only` |


      ### Headers


      |Header|Parameter|Description|

      |-|-|-|

      |`X-Auth-Client`|`client_id`|Obtained by creating an API account or
      installing an app in a BigCommerce control panel.|

      |`X-Auth-Token`|`access_token `|Obtained by creating an API account or
      installing an app in a BigCommerce control panel.|


      ### Example


      ```http

      GET /stores/{$$.env.store_hash}/v3/catalog/summary

      host: api.bigcommerce.com

      Content-Type: application/json

      X-Auth-Client: {client_id}

      X-Auth-Token: {access_token}

      ```


      * For more information on Authenticating BigCommerce APIs, see:
      [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication). 
parameters:
  Accept:
    name: Accept
    in: header
    type: string
    default: application/json
    required: true
  Content-Type:
    name: Content-Type
    in: header
    type: string
    default: application/json
    required: true
security:
  - X-Auth-Token: []
  - X-Auth-Client: []
x-stoplight:
  docs:
    includeDownloadLink: true
    showModels: false
