openapi: 3.0.0
info:
  title: Email Templates
  description: Manage Handlebars-based email templates globally and create channel-specific overrides.
servers:
  - url: 'https://api.bigcommerce.com'
    description: BigCommerce API Gateway
    variables:
      store_hash:
        default: abc123
        description: Store hash used to identify the store.
paths:
  '/stores/{store_hash}/v3/marketing/email-templates':
    get:
      summary: Get Email Templates
      description: |-
        Get a list of email templates.

        <!-- theme: info -->
        > #### Note
        >`/marketing/email-templates` endpoints only work after opting into the new email management experience from your store's control panel. You can opt-in by visiting Email Templates. If you have already opted in, visiting the Email Templates page will return a `404` error, and you will be able to access the new Transactional Emails page.
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/EmailTemplatesCollection'
                  meta:
                    type: object
              examples:
                Example:
                  value:
                    data:
                      - type_id: account_reset_password_email
                        body: '<!DOCTYPE html> <html lang="en"> <head>     <meta charset="UTF-8">     <title>Title</title> </head> <body> <p>     {{lang "reset_password" name=store.name}} </p> <br/> <br/> <a href=''{{account.reset_password_link}}''>     {{account.reset_password_link}} </a>  </body> </html>'
                        translations:
                          - locale: en
                            keys:
                              reset_password: 'To change your customer account password at {name} please click this link or copy and paste it into your browser:'
                        subject: 'Reset your password at {{store.name}}'
                    meta: {}
          description: |
            An array of email templates on the store
      parameters:
        - $ref: '#/components/parameters/ChannelIdParam'
      operationId: getEmailTemplates
      tags:
        - Email Templates
    parameters:
      - schema:
          type: string
        name: store_hash
        in: path
        required: true
  '/stores/{store_hash}/v3/marketing/email-templates/{template-name}':
    parameters:
      - schema:
          type: string
        name: template-name
        in: path
        required: true
      - schema:
          type: string
        name: store_hash
        in: path
        required: true
    get:
      summary: Get an Email Template
      description: |-
        Get a single global email template or a channel-specific email template override.


        <!-- theme: info -->
        > #### Note
        >`/marketing/email-templates` endpoints only work after opting into the new email management experience from your store's control panel. You can opt-in by visiting [Email Templates](https://login.bigcommerce.com/deep-links/manage/marketing/email-templates). If you have already opted in, visiting the [Email Templates](https://login.bigcommerce.com/deep-links/manage/marketing/email-templates) page will return a `404` error, and you will be able to access the new [Transactional Emails](https://login.bigcommerce.com/deep-links/manage/transactional-emails) page.
      tags:
        - Email Templates
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/EmailTemplate'
                  meta:
                    type: object
              examples:
                Example:
                  value:
                    data:
                      type_id: account_reset_password_email
                      body: '<!DOCTYPE html> <html lang="en"> <head>     <meta charset="UTF-8">     <title>Title</title> </head> <body> <p>     {{lang "reset_password" name=store.name}} </p> <br/> <br/> <a href=''{{account.reset_password_link}}''>     {{account.reset_password_link}} </a>  </body> </html>'
                      translations:
                        - locale: en
                          keys:
                            reset_password: 'To change your customer account password at {name} please click this link or copy and paste it into your browser:'
                      subject: 'Reset your password at {{store.name}}'
                    meta: {}
      operationId: getEmailTemplate
      parameters:
        - $ref: '#/components/parameters/ChannelIdParam'
    put:
      summary: Update a Template
      description: Update a global template or create a channel-specific email template override.
      tags:
        - Email Templates
      operationId: updateEmailTemplate
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/EmailTemplate'
                  meta:
                    type: object
              examples:
                Example:
                  value:
                    data:
                      type_id: account_reset_password_email
                      body: '<!DOCTYPE html> <html lang="en"> <head>     <meta charset="UTF-8">     <title>Title</title> </head> <body> <p>     {{lang "reset_password" name=store.name}} </p> <br/> <br/> <a href=''{{account.reset_password_link}}''>     {{account.reset_password_link}} </a>  </body> </html>'
                      translations:
                        - locale: en
                          keys:
                            reset_password: 'To change your customer account password at {name} please click this link or copy and paste it into your browser:'
                      subject: 'Reset your password at {{store.name}}'
                    meta: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      parameters:
        - $ref: '#/components/parameters/ChannelIdParam'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailTemplate'
            examples:
              Example:
                value:
                  type_id: account_reset_password_email
                  body: '<!DOCTYPE html> <html lang="en"> <head>     <meta charset="UTF-8">     <title>Title</title> </head> <body> <p>     {{lang "reset_password" name=store.name}} </p> <br/> <br/> <a href=''{{account.reset_password_link}}''>     {{account.reset_password_link}} </a>  </body> </html>'
                  translations:
                    - locale: en
                      keys:
                        reset_password: 'To change your customer account password at {name} please click this link or copy and paste it into your browser:'
                  subject: 'Reset your password at {{store.name}}'
        description: ''
    delete:
      summary: Delete Email Template Override
      description: Removes a channel-specific email template override.
      tags:
        - Email Templates
      operationId: deleteEmailTemplateOverride
      responses:
        '200':
          description: OK
      parameters:
        - $ref: '#/components/parameters/RequiredChannelIdParamForDelete'
components:
  schemas:
    ErrorResponse:
      allOf:
        - $ref: '#/components/schemas/BaseError'
        - type: object
          properties:
            errors:
              $ref: '#/components/schemas/DetailedErrors'
      x-internal: true
    BaseError:
      type: object
      description: |
        Error payload for the BigCommerce API.
      properties:
        status:
          description: |
            The HTTP status code.
          type: integer
        title:
          description: |
            The error title describing the particular error.
          type: string
        type:
          type: string
        instance:
          type: string
      x-internal: true
    DetailedErrors:
      type: object
      additionalProperties:
        type: string
      x-internal: true
    EmailTemplatesCollection:
      title: EmailTemplatesCollection
      type: array
      items:
        $ref: '#/components/schemas/EmailTemplate'
      description: A collection of all email templates.
      x-internal: true
    EmailTemplate:
      title: EmailTemplate
      type: object
      description: Data for a particular email template
      properties:
        type_id:
          type: string
          enum:
            - abandoned_cart_email
            - account_details_changed_email
            - combined_order_status_email
            - createaccount_email
            - createguestaccount_email
            - giftcertificate_email
            - invoice_email
            - ordermessage_notification
            - return_confirmation_email
            - return_statuschange_email
            - product_review_email
            - account_reset_password_email
          example: account_reset_password_email
        body:
          type: string
          example: '<!DOCTYPE html> <html lang="en"> <head>     <meta charset="UTF-8">     <title>Title</title> </head> <body> <p>     {{lang "reset_password" name=store.name}} </p> <br/> <br/> <a href=''{{account.reset_password_link}}''>     {{account.reset_password_link}} </a>  </body> </html>'
        translations:
          $ref: '#/components/schemas/LocaleCollection'
        subject:
          type: string
          example: 'Reset your password at {{store.name}}'
      x-internal: true
    LocaleObject:
      title: LocaleObject
      type: object
      properties:
        locale:
          type: string
          example: en
          description: 'Locale code for this language, such as ''en'', ''en-us'', ''fr-ca''.'
        keys:
          type: object
          example:
            reset_password: 'To change your customer account password at {name} please click this link or copy and paste it into your browser:'
          description: Language keys for the template. User-defined. Should match any lang keys used in the template.
      description: A particular locale's translations.
      x-internal: true
    LocaleCollection:
      title: LocaleCollection
      type: array
      items:
        $ref: '#/components/schemas/LocaleObject'
      description: A collection of locale translations for the static language.
      x-internal: true
    EmailTemplateUpdate:
      title: EmailTemplateUpdate
      type: object
      description: Data for updated template
      properties:
        body:
          type: string
          example: '<!DOCTYPE html> <html lang="en"> <head>     <meta charset="UTF-8">     <title>Title</title> </head> <body> <p>     {{lang "reset_password" name=store.name}} </p> <br/> <br/> <a href=''{{account.reset_password_link}}''>     {{account.reset_password_link}} </a>  </body> </html>'
        translations:
          $ref: '#/components/schemas/LocaleCollection'
        subject:
          type: string
          example: 'Reset your password at {{store.name}}'
      required:
        - body
        - lang
        - subject
      x-internal: true
    scratch:
      title: scratch
      type: object
      properties:
        id:
          type: string
      x-internal: true
  parameters:
    ChannelIdParam:
      in: query
      name: channel_id
      schema:
        type: integer
      description: 'Channel ID to use for channel-specific setting. If omitted, you will interact with the global setting only.'
    RequiredChannelIdParamForDelete:
      in: query
      name: channel_id
      schema:
        type: integer
      description: 'Required Channel ID. This delete operation will delete overridden settings for this channel, thus restoring them to the global defaults.'
      required: true
  securitySchemes:
    X-Auth-Token:
      name: X-Auth-Token
      type: apiKey
      in: header
      description: |-
        Authenticate requests by including an [OAuth](/api-docs/getting-started/authentication/rest-api-authentication#oauth-scopes) `access_token` in the request header.

        ```http
        GET /stores/{{STORE_HASH}}/v3/marketing/email-templates
        host: api.bigcommerce.com
        Accept: application/json
        X-Auth-Token: {{ACCESS_TOKEN}}
        ```

        ### OAuth Scopes
        |  **UI Name** | **Permission** | **Parameter** |
        | --- | --- | --- |
        |  Information & Settings | modify | `store_v2_information` |
        |  Information & Settings | read-only | `store_v2_information_read_only` |
security:
  - X-Auth-Token: []
